version: '2'
services:
  db:
    image: mysql
    restart: always
    volumes:
      - data:/var/lib/mysql:rw
    environment:
      MYSQL_ROOT_PASSWORD: r00t
      MYSQL_DATABASE: modx
    ports:
      - 33060:3306
    command: mysqld --sql-mode=NO_ENGINE_SUBSTITUTION
  nginx:
    image: alroniks/nginx:latest
    restart: always
    ports:
      - 3333:80
    volumes_from:
      - php
  php:
    build: ./modx/
    restart: always
    volumes:
      - ./src:/var/www/html/public
    depends_on:
      - db
    links:
      - db
volumes:
  data:
    driver: local
